[package]
name = "tsify"
version = "0.2.0"
edition = "2021"
authors = ["Madono Haru <madonoharu@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Tsify is a library for generating TypeScript definitions from rust code."
repository = "https://github.com/madonoharu/tsify"
homepage = "https://github.com/madonoharu/tsify"
keywords = ["wasm", "wasm-bindgen", "typescript"]
categories = ["wasm"]

[dependencies]
tsify-macros = { path = "tsify-macros", version = "0.2.0" }
wasm-bindgen = "0.2.80"

[dev-dependencies]
indoc = "1.0.4"
macrotest = "1.0.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }

[features]
default = ["wasm-bindgen-impl"]
wasm-bindgen-impl = ["tsify-macros/wasm-bindgen-impl"]

[workspace]
members = ["tsify-macros"]
